<!doctype html>
<html lang="pt-BR">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  
</head>

<body>


    <div class="container-fluid mt-2 ">
        <div class="row bg-warning">
                MENSAGENS
        </div>

        <div class="row bg-success d-none d-md-block d-sm-none">TOTAIS
        </div>
        <div class="row bg-light">
            <div class="col-sm-10" style="text-align:left">
                <h2>Aplicativo</h2>
            </div>

            <div class="col-sm-2" style="text-align:right">
                <a href="aplicativo_inserir.php" role="button" class="btn btn-success"><i
                        class="bi bi-plus-square"></i>&nbsp Novo</a>
            </div>
        </div>

        <div class="table bg-body mt-3" style="width: 100%; height: 75vh; overflow-y:scroll; overflow-x:auto;">
      
                </tr>

                <table class="table table-hover table-sm align-middle">
                    <thead class="table-light">
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                            <th>Points</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>
                        <tr>
                            <td>Adam</td>
                            <td>Johnson</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                            <td>67</td>
                        </tr>

                    </tbody>
                </table>


          
        </div>

    </div>
   

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

</body>

</html>